server:
  port: 8081

spring:
  application:
    name: goods

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/changgou
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://gqz2019.top:8090/eureka

  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
logging:
  level:
    com.gqz: debug